### ISSUE TITLE
Use reified inline functions instead of manually double wrapping

### ISSUE THREAD

**Issue by ToppleTheNun** [kursivee/android-authentication#10]
https://github.com/kursivee/android-authentication/blob/bf3f32179fd46dc881872813018521f7b6c17ef4/app/src/main/java/com/kursivee/authentication/domain/LoginCache.kt#L16

```
class MemoryCache {
    // ...
    
    inline fun <reified T> get(): T? = get(T::class.java) as? T
}
```

**Comment by kursivee** [comment]
Ah yes, I was messing around with something similar castornull but then I couldn't remember exactly what it was

**Comment by ToppleTheNun** [comment]
You also really shouldn't be caching the whole response, just the successful data portion. Don't wanna cache failures, right?

**Comment by kursivee** [comment]
The idea I had was to make the cache as dumb as possible. The [LoginRepository](https://github.com/kursivee/android-authentication/blob/bf3f32179fd46dc881872813018521f7b6c17ef4/app/src/main/java/com/kursivee/authentication/domain/LoginRepository.kt) is what I used to ensure errors weren't cached.

**Comment by kursivee** [comment]
NVM I think isee what you're saying

**Comment by kursivee** [comment]
Feex
https://github.com/kursivee/android-authentication/commit/9729d24721922d56d72fe0a546be6e49d1062c06
