### ISSUE TITLE
`val`s are named confusingly

### ISSUE THREAD

**Issue by ToppleTheNun** [kursivee/android-authentication#8]
https://github.com/kursivee/android-authentication/blob/bf3f32179fd46dc881872813018521f7b6c17ef4/app/src/main/java/com/kursivee/authentication/data/di/DataModule.kt#L10

Named modules but clearly only returns one module.

**Comment by kursivee** [comment]
Feex https://github.com/kursivee/android-authentication/commit/89c22c9817d2eb05d5cf6be41400d9a790436208
