### ISSUE TITLE
Wildcard Imports

### ISSUE THREAD

**Issue by ToppleTheNun** [kursivee/android-authentication#9]
https://github.com/kursivee/android-authentication/blob/bf3f32179fd46dc881872813018521f7b6c17ef4/app/src/test/java/com/kursivee/authentication/view/login/LoginViewModelTest.kt#L11

You sicken me.

**Comment by kursivee** [comment]
ROFL HAHAHAHAH.

**Comment by kursivee** [comment]
While I would normally agree... NAAAAA
